title: Khoi Bui Dinh
logo: /assets/img/self.jpeg
alt_logo: /assets/img/image_placeholder.jpg
description: bioinformatics | genomics research
theme: jekyll-theme-minimal

github: imkhoibui
github.logo: /assets/img/github_logo.png
cv_show: false
cv: /files/resume.pdf

baseurl: ""

collections:
  projects:
    output: true