title: Khoi Bui Dinh
logo: /assets/img/self.jpeg
description: bioinformatics | genomics research
theme: jekyll-theme-minimal

github: imkhoibui
github.logo: /assets/img/github_logo.png
cv_show: true
cv: /files/resume.pdf