title: Khoi Bui Dinh
logo: /assets/img/self.jpeg
alt_logo: /assets/img/bioinformatics.png
theme: jekyll-theme-minimal

github: imkhoibui
github.logo: /assets/icon/github_logo.png
cv_show: false
cv: /files/resume.pdf

baseurl: "/personal-webpage"

collections:
  projects:
    output: false